Repository mistercanderson/fitlit, pull requests merged in 2021-04, with the labels that each got.

#18 Test/sleep
  data/fakeSleep.js
  src/Sleep.js
  test/Sleep-test.js
Labels: Data

#19 Test/hydration
  data/fakeHydrationData.js
  src/Hydration.js
  src/index.html
  test/Hydration-test.js
Labels: Data, Iteration 2

#21 Charts
  data/fakeSleep.js
  package-lock.json
  package.json
  src/Hydration.js
  src/Sleep.js
  src/UserRepository.js
  src/index.html
  src/scripts.js
  src/styles.css
  test/Sleep-test.js
Labels: Dashboard

#23 Styling
  index.html
  src/scripts.js
  src/styles.css
Labels: Dashboard

#24 Test/activity
  data/fakeActivityData.js
  data/fakeUserData.js
  src/Activity.js
  src/Hydration.js
  src/scripts.js
  test/Activity-test.js
  test/Hydration-test.js
  test/Sleep-test.js
  test/User-test.js
  test/UserRepository-test.js
Labels: Data, Iteration 4

#25 Chart/activity
  data/fakeActivityData.js
  index.html
  src/Activity.js
  src/scripts.js
Labels: Dashboard, Iteration 4

#26 Change chart render to click event
  index.html
  src/scripts.js
Labels: Dashboard

#27 Change card styling when in chart mode
  src/scripts.js
  src/styles.css
Labels: Dashboard

#29 Dashboard/activity display
  index.html
  src/Activity.js
  src/scripts.js
Labels: Dashboard, Iteration 4

#32 Dashboard/activity charts
  src/scripts.js
  src/styles.css
Labels: Dashboard, Iteration 4
